[package]
name = "my_chess"
version = "0.1.0"
edition = "2018"

[profile.dev]
# Since neither me or Luke uses a debugger, turning off debug info should speed up compile times (although it does make debugging shaders a bit more difficult)
opt-level = 0

[profile.release]
opt-level = 3
# You don't need overflow checks if your ints never overflow *taps head*
overflow-checks = false
lto = "fat"
panic = "abort"
debug = 0
codegen-units = 1

[dependencies]
macroquad = "0.3"
